### ISSUE TITLE
Hello, writer. May i ask do you have the mini7games last 5 pictures of the game 

### ISSUE THREAD

**Issue by miqianmimi** [islamelnabarawy/sc2gym#1]
Cause i only see the map of "SC2CollectMineralShards" and "MoveToBeacon"

**Comment by islamelnabarawy** [comment]
I'm sorry, I don't understand your question. Do you mean that you are looking for code for the other mini-games? I don't have that here yet, unfortunately.

**Comment by miqianmimi** [comment]
Yes. That's exactly what i mean . i'd like to know if you have the code for the other 5 mini-games besides "SC2CollectMineralShards" and "MoveToBeacon".

**Comment by islamelnabarawy** [comment]
I don't, unfortunately. I have been too busy with other projects and haven't had a chance to contribute more code to this project yet.

I anticipate more progress on this during the last quarter of 2018. Please feel free to watch this repository to receive notifications when more code is posted.
