### ISSUE TITLE
Can you play against others? #25

### ISSUE THREAD

**Issue by Juphex** [islamelnabarawy/sc2gym#3]
Hey, 
good job:) 
Can you actually play against others? If yes, how ?

**Comment by islamelnabarawy** [comment]
Can you please clarify what you mean by play against others?

This library is meant to be an OpenAI Gym-compatible environment that would allow you to start writing reinforcement learning agents for StarCraft2. The agents you develop can play against the built-in AI in 1v1 mode or play the single-player minigames. If you are looking for human vs. human gameplay, you can just use the actual StarCraft game to do that. This particular library does not support human vs. agent or agent vs. agent gameplay; please see https://github.com/Dentosal/python-sc2 and https://github.com/deepmind/pysc2 for ways to do that. This is meant to be a simple and uncomplicated starting point, but there are other more advanced libraries out there for experienced users.

I hope this answers your question. If not, please clarify more and I would be happy to try and help.

**Comment by Juphex** [comment]
This helped quite a lot. Do you think an AI written with your Lib is easy to port into the one from Deepmind?

**Comment by islamelnabarawy** [comment]
It should be easy to port into pysc2 without too much effort, yes.
